name: deploy to gcp
on: [push]
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: "//iam.googleapis.com/projects/619881049050/locations/global/workloadIdentityPools/github-action-pool/providers/github-provider"
        service_account: 'github-gcp-sa@touchless-364916.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'github-actions'
        runtime: 'nodejs16'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
