name: deploy to gcp
on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: "projects/619881049050/locations/global/workloadIdentityPools/github-gcp-pool/providers/github-provider"
        service_account: 'github-gcp-sa@touchless-364916.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'cloud-function-version-control'
        runtime: 'nodejs16'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
