name: deploy to gcp
on: [push]
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/619881049050/locations/global/workloadIdentityPools/github-pool/github-provider'
        service_account: 'github-actions@touchless-364916.iam.gserviceaccount.com'

    - id: 'deploy'
      name: 'Deployment started'
      uses: 'google-github-actions/deploy-cloud-functions@main'
      with:
        project_id: touchless-364916
        name: 'github-action'
        runtime: 'nodejs16'
